services:
    django:
        build: .
        container_name: django_ixvan
        command: >        
            sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
        volumes:
            - .:/app
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            CELERY_BROKER: ${CELERY_BROKER}
            CELERY_BACKEND: ${CELERY_BACKEND}
        ports:
            -   "8000:8000"
        depends_on:
            -   pgdb
            -   redis
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            -   "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            -   pgdata:/var/lib/postgresql/data/
    celery:
        build: .
        command: celery -A config worker -l info
        volumes:
            - .:/app
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        command: celery -A config beat -l info
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: "redis:alpine"
volumes:
  pgdata: